baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'TaigaChat'
enableRobotsTXT = true


[params]
Description = 'TaigaChat is a decentralized app for community-oriented communication. Build an online presence where only you can define the rules!'
Repo = 'https://github.com/taigachat'
TwitterImage = 'favicon.png'
TwitterSite = '@taigachatcom'
Image = 'favicon.png'
